# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

likelihood <- function(onset, cut, table, alpha, beta, gamma, epsilon, index, esteps) {
    .Call(`_SIRmcmc_likelihood`, onset, cut, table, alpha, beta, gamma, epsilon, index, esteps)
}

logLikelihood <- function(onset, cut, hh, table, alpha, beta, gamma, epsilon, followup, index, esteps) {
    .Call(`_SIRmcmc_logLikelihood`, onset, cut, hh, table, alpha, beta, gamma, epsilon, followup, index, esteps)
}

unifprior <- function(alpha, beta, gamma, epsilon, esteps, UB = 1000, LB = 0.01) {
    .Call(`_SIRmcmc_unifprior`, alpha, beta, gamma, epsilon, esteps, UB, LB)
}

